#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides: tis-waptserver
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts the uwsgi app server for tis-waptserver
# Description: starts uwsgi app server for tis-waptserver
### END INIT INFO
set -e

VERSION=waptserver
PATH=/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/$VERSION
RUN=/var/run
NAME=$VERSION
CONFIG_FILE=/opt/wapt/waptserver/waptserver.ini
LOGFILE=/var/log/$NAME.log
OWNER=wapt
GROUP=www-data
DESC=$VERSION
OP=$1

unset http_proxy
unset https_proxy

DAEMON_OPTS=""

# Include uwsgi defaults if available
if [[ -f /etc/default/$VERSION ]]; then
    . /etc/default/$VERSION
fi

do_pid_check()
{
    local PIDFILE=$1
    [[ -f $PIDFILE ]] || return 0
    local PID=$(cat $PIDFILE)
    for p in $(pgrep uwsgi-core); do
        [[ $p == $PID ]] && return 1
    done
    return 0
}


do_start()
{
	local PIDFILE=$RUN/$NAME.pid
	if do_pid_check $PIDFILE; then
		/usr/bin/uwsgi-core -d $LOGFILE --pidfile $PIDFILE --ini $CONFIG_FILE --uid $OWNER --gid $GROUP --plugin http,python
	else
		echo "Already running!"
	fi
}

send_sig()
{
        local PIDFILE=$RUN/$NAME.pid
        set +e
        [[ -f $PIDFILE ]] && kill $1 $(cat $PIDFILE) > /dev/null 2>&1
        set -e
}

wait_and_clean_pidfiles()
{
        local PIDFILE=$RUN/$NAME.pid
        local timeout=70 # 7 seconds loop
        until do_pid_check $PIDFILE || [ "$timeout" -le 0 ]; do
            sleep 0.1
            echo -n .
            timeout=$(($timeout - 1))
        done
        if ! do_pid_check $PIDFILE; then
            echo " WAPTserver killed with much prejudice"
            send_sig -KILL
        fi
        rm -f $PIDFILE
}

do_stop()
{
    send_sig -QUIT
    wait_and_clean_pidfiles
}

do_reload()
{
    send_sig -HUP
}

do_force_reload()
{
    send_sig -TERM
}

get_status()
{
    send_sig -USR1
}

case "$OP" in
    start)
        echo "Starting $DESC: "
        do_start
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        do_stop
        echo "$NAME."
        ;;
    reload)
        echo -n "Reloading $DESC: "
        do_reload
        echo "$NAME."
        ;;
    force-reload)
        echo -n "Force-reloading $DESC: "
        do_force_reload
        echo "$NAME."
       ;;
    restart)
        echo "Restarting $DESC: "
        do_stop
        do_start
        echo "$NAME."
        ;;
    status)
        get_status
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|reload|force-reload|status}" >&2
        exit 1
        ;;
esac
exit 0

