#!/usr/bin/python

import subprocess
import os
import shutil
import sys
import time
import errno

def run(*args, **kwargs):
    return subprocess.check_output(*args, shell=True, **kwargs)

print("Setting up pid and log files")
run('touch /var/log/waptservice.log')
run('touch /var/run/waptservice.pid')
run('chown wapt:admin /var/log/waptservice.log')
run('chmod 640 /var/log/waptservice.log')

# minimal .profile script to setup python path
open('/opt/wapt/.profile','w').write("""#
export PYTHONHOME=/opt/wapt
export PYTHONPATH=/opt/wapt
export PATH=/opt/wapt/bin:$PATH
""")

run('rm -f /opt/wapt/*.pyc')
run('rm -f /opt/wapt/waptserver/*.pyc')

# relocating waptserver.ini config file to the new location

print("Tightening up permissions")
run('find /opt/wapt -type f -exec chmod 644 {} +')
run('find /opt/wapt -type d ! -name conf ! -name log -exec chmod 755 {} +')
run('find /opt/wapt -type d ! -name conf ! -name log -exec chown root:admin {} +')
run('chown -R wapt:admin /opt/wapt/conf')
run('chown -R wapt:admin /opt/wapt/db')
run('chmod 750 /opt/wapt/conf')
run('chown -R wapt:admin /opt/wapt/log')
run('chmod 755 /opt/wapt/log')
run('chmod 755 /opt/wapt/bin/*')
if not(os.path.isdir('/opt/wapt/private')):
    os.mkdir('/opt/wapt/private')
run('chown -R root /opt/wapt/private')
run('chmod -R 700 /opt/wapt/private')

print("Add script for session-setup")
run("defaults write com.apple.loginwindow LoginHook /opt/wapt/session-setup.sh")

os.chmod('/opt/wapt/runwaptservice.sh',0o755)
os.chmod('/usr/local/bin/waptpython',0o755)
os.chmod('/opt/wapt/wapt-get.sh',0o755)
# waptexit
run('sudo launchctl load -w /Library/LaunchDaemons/waptexit.plist')
