#!/usr/bin/python

import subprocess
import os
import shutil
import sys
import time
import errno

def run(*args, **kwargs):
    return subprocess.check_output(*args, shell=True, **kwargs)

print("Setting up pid and log files")
run('touch /var/log/waptagent.log')
run('touch /var/run/waptagent.pid')
run('chown wapt:admin /var/log/waptagent.log')
run('chmod 640 /var/log/waptagent.log')

# minimal .profile script to setup python path
open('/opt/wapt/.profile','w').write("""#
export PYTHONHOME=/opt/wapt
export PYTHONPATH=/opt/wapt
export PATH=/opt/wapt/bin:$PATH
""")

run('rm -f /opt/wapt/*.pyc')
run('rm -f /opt/wapt/waptserver/*.pyc')

# relocating waptserver.ini config file to the new location

NEW_CFG_PATH = '/opt/wapt/conf/waptagent.ini'

print("Tightening up permissions")
run('find /opt/wapt -type f -exec chmod 644 {} +')
run('find /opt/wapt -type d ! -name conf ! -name log -exec chmod 755 {} +')
run('find /opt/wapt -type d ! -name conf ! -name log -exec chown root:admin {} +')
run('chown -R wapt:admin /opt/wapt/conf')
run('chown -R wapt:admin /opt/wapt/db')
run('chmod 750 /opt/wapt/conf')
run('chown -R wapt:admin /opt/wapt/log')
run('chmod 755 /opt/wapt/log')
run('chmod 755 /opt/wapt/bin/*')

os.chmod('/opt/wapt/runwaptagent.sh',0o755)
os.chmod('/usr/local/bin/waptpython',0o755)
os.chmod('/opt/wapt/wapt-get.sh',0o755)

def force_symlink(target, link_name):
    try:
        os.symlink(target, link_name)
    except OSError, e:
        if e.errno == errno.EEXIST:
            os.remove(link_name)
            os.symlink(target, link_name)
        else:
            raise e

force_symlink('/opt/wapt/runwaptagent.sh', '/usr/local/bin/waptservice')
force_symlink('/opt/wapt/wapt-get.sh', '/usr/local/bin/wapt-get')

#try:
#    print "Restarting syslog-ng"
#    run('systemctl restart syslog-ng')
#except subprocess.CalledProcessError:
#    print "Restarting rsyslog"
#    run('systemctl restart rsyslog')

# restart server if conf file is there and if it was already running
#if os.path.exists('/opt/wapt/conf/wapt-get.ini'):
#    print("Restarting Agent")
#    run('systemctl restart waptagent.service')
