#!/bin/sh

umask 022

id -u wapt
if [ "$?" -eq 0 ] ; then
  echo "wapt user already exists, skipping user creation"
else
  echo "wapt user does not exists, creating user"
  useradd --system -g www-data wapt
fi

echo "Creating wapt root directory"
mkdir -p /var/www/wapt/
mkdir -p /var/www/waptdev/
mkdir -p /var/www/wapt-host
mkdir -p /var/www/wapt-group
mkdir -p /var/www/waptwua
mkdir -p /etc/tis

find /var/www/wapt /var/www/waptdev /var/www/wapt-host /var/www/wapt-group /var/www/waptwua \
    -type d -exec chown wapt:www-data {} ';'

chmod 755 /var/www/
chmod 755 /var/www/wapt/
chmod 755 /var/www/waptdev/
chmod 755 /var/www/wapt-host/
chmod 755 /var/www/waptwua/


/usr/bin/python /opt/wapt/wapt-scanpackages.py /var/www/wapt/
chmod a+x /opt/wapt/waptpackage.py
chmod a+x /opt/wapt/wapt-scanpackages.py

exit 0
