#!/bin/bash
echo "Creating wapt root diretory"
mkdir -p /var/www/wapt/
mkdir -p /var/www/wapt-host
mkdir -p /var/www/wapt-group
mkdir -p /etc/tis

chown wapt:www-data -R /var/www/wapt/
chown wapt:www-data -R /var/www/wapt-host
chown wapt:www-data -R /var/www/wapt-group

chmod g+ws /var/www/wapt/
chmod g+ws /var/www/wapt-host/
chmod g+ws /var/www/wapt-group/

chmod +x /opt/wapt/waptrepo/waptpackage.py
chmod +x /opt/wapt/waptrepo/wapt-scanpackages.py
/usr/bin/python /opt/wapt/wapt-scanpackages.py /var/www/wapt/
