#!/usr/bin/python
import os

if os.path.islink('/var/www/wapt/waptsetup.exe'):
    print 'hello'
    os.unlink('/var/www/wapt/waptsetup.exe')


if os.path.isfile('/var/www/wapt/waptsetup.exe'):
    os.remove('/var/www/wapt/waptsetup.exe')


if os.path.isfile('/var/www/wapt/waptsetup-tis.exe'):
    os.remove('/var/www/wapt/waptsetup-tis.exe')

if os.path.isfile('/var/www/wapt/waptsetup-tis.exe.old'):
    os.remove('/var/www/wapt/waptsetup-tis.exe.old')
