#!/usr/bin/python

import subprocess
import os
import shutil
import sys
import time


def run(*args, **kwargs):
    return subprocess.check_output(*args, shell=True, **kwargs)

run('systemctl enable  waptserver')

print("Setting up pid and log files")
run('touch /var/log/waptserver.log')
run('touch /var/run/waptserver.pid')
run('chown wapt:root /var/log/waptserver.log')
run('chmod 640 /var/log/waptserver.log')

# minimal .profile script to setup python path
open('/opt/wapt/.profile','w').write("""#
export PYTHONHOME=/opt/wapt
export PYTHONPATH=/opt/wapt
export PATH=/opt/wapt/bin:$PATH
""")

print("Cleaning up leftovers")
for cleanup_dir in ('rpm','mongodb','spool','uninstall_service.bat'):
    mypath = os.path.join('/opt/wapt/waptserver',cleanup_dir)
    if os.path.exists(mypath):
        shutil.rmtree(mypath)

run('rm -f /opt/wapt/*.pyc')
run('rm -f /opt/wapt/waptserver/*.pyc')

# relocating waptserver.ini config file to the new location
OLD_CFG_PATH = '/opt/wapt/waptserver/waptserver.ini'
NEW_CFG_PATH = '/opt/wapt/conf/waptserver.ini'
if os.path.exists(OLD_CFG_PATH) and not os.path.islink(OLD_CFG_PATH):
    try:
        print('relocating waptserver.ini conf file to /opt/wapt/con/waptserver.ini')
        os.rename(OLD_CFG_PATH, NEW_CFG_PATH)
        os.symlink(NEW_CFG_PATH, OLD_CFG_PATH)
    except Exception:
        pass

print("Tightening up permissions")
run('find /opt/wapt -type f -exec chmod 644 {} +')
run('find /opt/wapt -type f ! -name waptserver.ini -exec chown root:root {} +')
run('find /opt/wapt -type d ! -name conf ! -name log -exec chmod 755 {} +')
run('find /opt/wapt -type d ! -name conf ! -name log -exec chown root:root {} +')
run('chown -R wapt:root /opt/wapt/conf')
run('chown -R wapt:root /opt/wapt/db')
run('chmod 750 /opt/wapt/conf')
run('chown -R wapt:root /opt/wapt/log')
run('chmod 755 /opt/wapt/log')
run('chmod 755 /opt/wapt/bin/*')
run('mkdir -p /var/www/wapt/icons')
run('mkdir -p /var/www/wapt-host')
run('mkdir -p /var/www/wapt')
run('mkdir -p /var/www/waptwua')

# fix ownership bug of /var/www, need to find where it is screwed up
run('chown www-data:www-data /var/www')
run('chmod 755 /var/www')

run('chown -R wapt:www-data /var/www/wapt*')
run('chmod -R 750 /var/www/wapt*')
run("""echo "User-agent:*\nDisallow: /\n" > /var/www/robots.txt""")

os.chmod('/opt/wapt/wapt-scanpackages.py',0o755)
os.chmod('/opt/wapt/wapt-signpackages.py',0o755)
os.chmod('/opt/wapt/waptserver/scripts/postconf.sh',0o755)
os.chmod('/opt/wapt/waptserver/scripts/postconf.py',0o755)
os.chmod('/opt/wapt/waptserver/trigger_action.sh',0o755)

os.chmod('/usr/bin/wapt-scanpackages',0o755)
os.chmod('/usr/bin/wapt-signpackages',0o755)

os.chmod('/opt/wapt/runwaptserver.sh',0o755)
os.chmod('/opt/wapt/runwapttasks.sh',0o755)
os.chmod('/usr/bin/wapt-scanpackages', 0o755)
os.chmod('/usr/bin/wapt-signpackages', 0o755)
os.chmod('/usr/bin/waptpython',0o755)

try:
    print "Restarting syslog-ng"
    run('systemctl restart syslog-ng')
except subprocess.CalledProcessError:
    print "Restarting rsyslog"
    run('systemctl restart rsyslog')

def check_if_running(process_name):
    try:
        run('pgrep -f "%s" ' % process_name)

        return True
    except Exception:
        return False


# restart server if conf file is there and if it was already running
if os.path.exists('/opt/wapt/conf/waptserver.ini'):
    print("Restarting server")
    run('systemctl restart waptserver')
    run('systemctl restart wapttasks')

print("""
########################################################

Installation/Upgrade of waptserver is finished.

For postconfiguration please run:
/opt/wapt/waptserver/scripts/postconf.sh

########################################################
 """)
