#!/usr/bin/python3
import subprocess
import os

from pwd import getpwnam
import time

def check_user_exists(username):
    try:
        getpwnam(username)
        return True
    except:
        return False

def run(cmd):
    print("Executing : %s " % cmd)
    print(subprocess.check_output(cmd,shell=True))


#check if process is running and if so stop process. Should check pid , TODO : check for real service pid status
ps_out = str(subprocess.check_output('/bin/ps ax',shell=True))
if "/usr/bin/uwsgi-core" in ps_out:
    if os.path.isfile('/etc/init.d/waptserver'):
        run('/etc/init.d/waptserver stop')
    #ugly hack, wait for process to have stopped
    time.sleep(2)

# check for legacy (<0.9) install if user waptserver exists, then convert to simple wapt, otherwise create
# gid 33 = www-data
if check_user_exists('waptserver'):
    print("Waptserver user exists, renaming to wapt and changing group to www-data")
    run("/usr/sbin/usermod -l wapt waptserver")
    run("/usr/sbin/usermod -g 33 wapt")

if not check_user_exists('wapt'):
    print("Adding user wapt")
    run("adduser --system --home /opt/wapt  --gid 33 wapt")
else:
    print("User wapt already existing, skipping user creation")
    run("/usr/sbin/usermod -g 33 wapt")
