#!/bin/sh
rm -f /usr/bin/waptexit /usr/bin/waptself

xdg-icon-resource uninstall --size 16  --mode system tis-waptself
xdg-icon-resource uninstall --size 32  --mode system tis-waptself
xdg-icon-resource uninstall --size 64  --mode system tis-waptself
xdg-icon-resource uninstall --size 128  --mode system tis-waptself

xdg-icon-resource uninstall --size 16  --mode system tis-waptexit
xdg-icon-resource uninstall --size 32  --mode system tis-waptexit
xdg-icon-resource uninstall --size 64  --mode system tis-waptexit
xdg-icon-resource uninstall --size 128  --mode system tis-waptexit

xdg-desktop-menu  uninstall --mode system tis-waptself.desktop
xdg-desktop-menu  uninstall --mode system tis-waptdesktop.desktop

update-desktop-database