#!/usr/bin/python

import subprocess
import os
import shutil
import sys
import time


def run(*args, **kwargs):
    return subprocess.check_output(*args, shell=True, **kwargs)

run('rm -f /usr/bin/waptservice')
run('rm -f /usr/bin/wapt-get')