#!/usr/bin/python

import subprocess
import os
import shutil
import sys
import time


def run(*args, **kwargs):
    return subprocess.check_output(*args, shell=True, **kwargs)

run('rm -f /opt/wapt/*.pyc')
run('rm -rf /opt/wapt/cache')
run('rm -rf /opt/wapt/lib')
run('rm -rf /opt/wapt/waptservice')
run('rm -f /usr/bin/waptservice')
run('rm -f /usr/bin/wapt-get')
run('rm -f /opt/wapt/waptenterprise')