#!/usr/bin/python
import subprocess
import os

from pwd import getpwnam
import time

def check_user_exists(username):
    try:
        getpwnam(username)
        return True
    except:
        return False

if not check_user_exists('wapt'):
    print("Adding user wapt")
    cmd  = "adduser --system --home /opt/wapt  --gid 33 wapt"
    print("Executing : %s " % cmd)
    print(subprocess.check_output(cmd,shell=True))
else:
    print "User wapt already existing, skipping user creation"
    cmd = "/usr/sbin/usermod -g 33 wapt"
    print "EXECUTING : %s " %cmd
    print(subprocess.check_output(cmd,shell=True))
