#!/usr/bin/python

import subprocess
import os
import shutil
import sys
import time


def run(*args, **kwargs):
    return subprocess.check_output(*args, shell=True, **kwargs)

run('find /opt/wapt -name "*.pyc" -type f -delete')